# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [4]:
import numpy as np

#### 2. Print the numpy version

In [6]:
print(np.version.version)

2.2.2


#### 3. Create a null array of size 5

In [5]:
np.array([None,None,None,None,None])

array([None, None, None, None, None], dtype=object)

#### 4. Create a null array of size 15 but the seventh value which is 1

In [8]:
x = []
for i in range(15):
    if i == 14:
        x.append(1)
    else:
        x.append(None)

print(np.array(x))

[None None None None None None None None None None None None None None 1]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [13]:
a = np.arange(0, 16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [14]:
arr = np.array([1, 2, 4, 0, 4, 0])
x = np.where(arr == 0)
print(x)

(array([3, 5]),)


#### 7. Create a 4x4x4 array with random values

In [32]:
from numpy import random
a = random.rand(4,4,4)
print(a)

[[[0.07965219 0.84091112 0.41324215 0.37324121]
  [0.41706856 0.54722024 0.30782865 0.79995338]
  [0.41071317 0.62392857 0.68334805 0.86164669]
  [0.40352237 0.96342597 0.70235387 0.45679791]]

 [[0.34065816 0.46048847 0.87881994 0.3680335 ]
  [0.85824158 0.84828752 0.91281319 0.60236429]
  [0.06181935 0.39872226 0.37179768 0.28792278]
  [0.31599705 0.16650598 0.47542804 0.49444035]]

 [[0.72104005 0.00481479 0.64920495 0.83225911]
  [0.96925512 0.84440098 0.83931694 0.70106823]
  [0.99952496 0.30665456 0.95899006 0.2488705 ]
  [0.823172   0.89958463 0.79211982 0.61584686]]

 [[0.27413305 0.45328788 0.28183429 0.39996351]
  [0.08081985 0.60804423 0.38257664 0.38916748]
  [0.72669439 0.46479043 0.15705368 0.54075599]
  [0.34948554 0.15758826 0.96608464 0.8943756 ]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [45]:
array = np.random.rand(15,15)
print(array)
min = array.min()
max = array.max()
print("Minimum Value: ", min)
print("Maximum Value: ", max)

[[0.05170019 0.19590914 0.76297626 0.38447433 0.62750234 0.16725351
  0.50801837 0.55847606 0.51383501 0.08326749 0.79118229 0.33825868
  0.3978419  0.78143036 0.8956661 ]
 [0.57526804 0.87771122 0.45653417 0.65187067 0.24233237 0.315194
  0.80057511 0.10852976 0.29556371 0.19410715 0.4509251  0.47761125
  0.86100412 0.12727064 0.32470083]
 [0.86984702 0.47704363 0.05375982 0.69237246 0.07907709 0.37942894
  0.49986926 0.73254632 0.4094573  0.43904951 0.51100034 0.94458568
  0.24853789 0.32715498 0.62154791]
 [0.27193469 0.7701427  0.72046173 0.61816383 0.4347252  0.68394365
  0.99367696 0.8134871  0.30631209 0.33793095 0.76570248 0.79550622
  0.32762387 0.66223167 0.08830216]
 [0.77657449 0.88445844 0.24712939 0.5332462  0.190238   0.11069323
  0.37790566 0.48792235 0.58352047 0.98955587 0.18236406 0.40275423
  0.62835253 0.84533503 0.50157008]
 [0.4556847  0.31467854 0.91597232 0.63047954 0.91010516 0.00861698
  0.38012227 0.42207524 0.84943629 0.55502346 0.64859245 0.01758104
  0.49

#### 9. Create a random array of size 25 and find the mean value

In [ ]:
rand_num = np.random()

#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [4]:
import numpy as np

x = np.array([2, 4, 9])
y = np.array([1, 14, 6])

print("Array 1 = ", x) 
print("Array 2 = ", y)

Array 1 =  [2 4 9]
Array 2 =  [ 1 14  6]


10.1 What is the result of *a + b*?

In [6]:
import numpy as np

x = np.array([2, 4, 9])
y = np.array([1, 14, 6])

z = x + y

print("Result ", z)

Result  [ 3 18 15]


10.2 What is the result of *a - b*?

In [7]:
import numpy as np

x = np.array([2, 4, 9])
y = np.array([1, 14, 6])

z = x - y

print("Result ", z)

Result  [  1 -10   3]


10.3 What is the result of *a × b*?

In [8]:
import numpy as np

x = np.array([2, 4, 9])
y = np.array([1, 14, 6])

z = x * y

print("Result ", z)

Result  [ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [9]:
import numpy as np

x = np.array([2, 4, 9])
y = np.array([1, 14, 6])

z = x / y

print("Result ", z)

Result  [2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [12]:
import numpy as np

matrix = np.array([(10, 20, 30,),(40, 50, 60),(70,80,90)])

print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [14]:
import numpy as np

x = np.array([(10, 20, 30,),(40, 50, 60),(70,80,90)])

print("Extracted Element: ", x[1,1])

Extracted Element:  50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [16]:
import numpy as np

x = np.array([(10, 20, 30,),(40, 50, 60),(70,80,90)])

print("Second Row Extracted: ", x[1])

Second Row Extracted:  [40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [17]:
import numpy as np

x = np.array([(10, 20, 30,),(40, 50, 60),(70,80,90)])

print("Second Row Extracted: ", x[2])

Second Row Extracted:  [70 80 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [18]:
import numpy as np

x = np.array([(10, 20, 30,),(40, 50, 60),(70,80,90)])

x1 = x[1:3, 1:3]
print("Extracted Submatrix: ", x1)

Extracted Submatrix:  [[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [19]:
import numpy as np

x = np.array([(1, 2, 3, 4),(5, 6, 7, 8),(9, 10, 11, 12)])

print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [23]:
import numpy as np

x = np.array([(1, 2, 3, 4),(5, 6, 7, 8),(9, 10, 11, 12)])

x1 = x[1:3, 1:3]
print("Extracted SubArray: ", x1)

Extracted SubArray:  [[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [34]:
import numpy as np

x = np.array([(1, 2, 3, 4),(5, 6, 7, 8),(9, 10, 11, 12)])

x1 = x[0,[0, 2]]
print("Extracted SubArray: ", x1)

Extracted SubArray:  [1 3]


4. Write code to reverse the order of rows in the matrix

In [36]:
import numpy as np

x = np.array([(1, 2, 3, 4),(5, 6, 7, 8),(9, 10, 11, 12)])

x1 = np.flip(x)
print("Extracted SubArray: ", x1)

Extracted SubArray:  [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


5. Write code to extract the last two columns of the matrix.

In [40]:
import numpy as np

x = np.array([(1, 2, 3, 4),(5, 6, 7, 8),(9, 10, 11, 12)])

x1 = x[:, -2:]
print("Extracted SubArray: ", x1)

Extracted SubArray:  [[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [41]:
import numpy as np

matrix = np.array([(11, 7, 33,),(44, 5, 18)])

print(matrix)

[[11  7 33]
 [44  5 18]]


2. Write code to join arr1 and arr2 into a single 1D array.

In [45]:
import numpy as np

matrix = np.array([11, 7, 33])
matrix2 = np.array([44, 5, 18])

result = np.concatenate((matrix, matrix2))
print(result)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [50]:
import numpy as np

matrix = np.array([11, 7, 33])
matrix2 = np.array([44, 5, 18])

result = np.stack((matrix, matrix2), axis=1)
print(result)

[[11 44]
 [ 7  5]
 [33 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [57]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.vstack((matrix))
result = np.vstack((matrix2))
print("Array 1: ", result)
print("Array 2: ", result)

Array 1:  [[5 6]
 [7 8]]
Array 2:  [[5 6]
 [7 8]]


5. Write code to join them horizontally (column-wise).

In [58]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.hstack((matrix, matrix2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [59]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.vstack((matrix, matrix2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [61]:
import numpy as np

x = np.arange(10, 29, 2)
x1 = np.random.randint(1, 51, size=(4,4))
x2 = np.ones((2, 3, 4))

print(x)
print(x1)
print(x2)

[10 12 14 16 18 20 22 24 26 28]
[[45 35 31 41]
 [45 32 33 26]
 [14 27 22 27]
 [16 16 37  6]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [64]:
import numpy as np

x = np.array([10, 12, 14, 16, 18, 20])
y = np.array([[45, 35, 31, 41], [45, 32, 33, 26], [14, 27, 22, 27], [16, 16, 37,  6]])
x1 = y[:, -2:]
x_reshape = x.reshape(2, -1)
y[y % 2 == 0] = -1
print(x_reshape)
print(x1)
print(y)

[[10 12 14]
 [16 18 20]]
[[31 41]
 [33 -1]
 [-1 27]
 [37 -1]]
[[45 35 31 41]
 [45 -1 33 -1]
 [-1 27 -1 27]
 [-1 -1 37 -1]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [69]:
import numpy as np

x = np.array([[45, 35, 31, 41], [45, 32, 33, 26], [14, 27, 22, 27], [16, 16, 37,  6]])

mean = np.mean(x)
median = np.median(x)
std_dev = np.std(x)
sums = np.sum(x, axis=1)
max_val = np.max(x)
max_arg = np.argmax(x)

print("Mean: ", mean)
print("Median: ", median)
print("Standard Devation: ", std_dev)
print("Sum of All Number: ", sums)
print("Maximum Value: ", max_val)
print("Maximum Index: ", max_arg)

Mean:  28.3125
Median:  29.0
Standard Devation:  10.998401872544939
Sum of All Number:  [152 136  90  75]
Maximum Value:  45
Maximum Index:  0


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [95]:
import numpy as np
from numpy import random

x = np.random.random((10, 10))
min = x.min(axis=0)
max = x.max(axis=0)

print(x)
print("Minimum: ", min)
print("Maximum: ", max)

[[0.0316024  0.27936147 0.93682798 0.94425155 0.31362199 0.1401826
  0.51254379 0.34147725 0.40875528 0.69850041]
 [0.21138155 0.52107036 0.41169966 0.06816525 0.260819   0.58781573
  0.90828742 0.49713416 0.89575282 0.63335591]
 [0.04390725 0.06132835 0.04199733 0.72662268 0.34304256 0.66031334
  0.33263998 0.30832331 0.72334239 0.31750245]
 [0.89524125 0.26838162 0.36760219 0.0812893  0.6655046  0.23815965
  0.65523753 0.32346937 0.25506469 0.85047449]
 [0.88299007 0.66682553 0.29265943 0.66156671 0.17629589 0.25935643
  0.17029684 0.22031301 0.4523808  0.78513615]
 [0.20819947 0.87262063 0.03493106 0.26586688 0.37191496 0.74344113
  0.81247695 0.68706644 0.50587292 0.8954511 ]
 [0.79180989 0.1761351  0.41729016 0.95344865 0.95272125 0.0550087
  0.36969948 0.29594256 0.65377397 0.31035301]
 [0.14521998 0.65276692 0.17789793 0.80717704 0.28467925 0.98497549
  0.45998685 0.56985776 0.24311373 0.20261609]
 [0.74470767 0.33079624 0.2238456  0.71834339 0.81936182 0.49963059
  0.50946354 0